- id: markdown-detect-nonref-links
  name: Checking for Markdown non-ref links
  description: |
    This pre-commit hook detects markdown files that contain non-ref link
    types.
  entry: markdown-detect-nonref-links
  language: python
  files: '\.md$'
