repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: fix-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-json
    -   id: pretty-format-json
        args: ["--autofix"]
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: debug-statements
    -   id: detect-private-key
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.0
    hooks:
    -   id: codespell
-   repo: https://github.com/p15r/pre-commit-hooks.git
    rev: v0.4.0
    hooks:
    -   id: prevent-commit-to-default-branch
    -   id: markdown-detect-nonref-links
        exclude: |
            (?x)^(
                tests/.*
            )$
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.1
    hooks:
      - id: gitleaks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
    -   id: mypy
        args: ["--strict", "--install-types", "--non-interactive", "--ignore-missing-imports"]
        exclude: |
            (?x)^(
                tests/.*
            )$
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-use-type-annotations
    -   id: python-no-eval
    -   id: python-no-log-warn
# Note: bandit replaced by ruff
# -   repo: https://github.com/PyCQA/bandit
#     rev: 1.7.9
#     hooks:
#     -   id: bandit
#         args: [--exclude, tests/]
# Note: use `ruff --fix` instead
# -   repo: https://github.com/asottile/reorder_python_imports
#     rev: v3.12.0
#     hooks:
#     -  id: reorder-python-imports
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.2
  hooks:
    - id: ruff
      args: [ --fix ]
      exclude: |
            (?x)^(
                tests/.*
            )$
    - id: ruff-format
      exclude: |
            (?x)^(
                tests/.*
            )$
