- id: markdown-detect-nonref-links
  name: Checking for Markdown non-ref links
  description: |
    This pre-commit hook detects markdown files that contain non-ref link
    types.
  entry: markdown-detect-nonref-links
  language: python
  files: '\.md$'
- id: rego-unsafe-boolean-comparison
  name: Checking for unsafe boolean comparisons in Rego
  description: |
    This pre-commit hook detects unsafe boolean comparisons in Rego that
    could potential cause false-positive and false-negative alerts.
  entry: rego-unsafe-boolean-comparison
  language: python
  files: '\.rego$'
- id: docker-multiline-cmds
  name: Checking for suboptimal use of multiline commands in Dockerfiles
  description: |
    This pre-commit hook detects suboptimal use of multiline commands in
    Dockerfiles. Suboptimal in the sense that if changing them creates
    unclean git diffs.
    More information on https://www.youtube.com/watch?v=BdxdRlTnPEE
  entry: docker-multiline-cmds
  language: python
  types: ['dockerfile']
- id: prevent-push-to-default-branch
  name: protect default branch
  description: |
    This pre-commit hook prevents pushing to the default branch.
    It should be the first hook in your pre-commit config.
  entry: prevent-commit-to-default-branch
  language: python
  always_run: true
  stages: [pre-push, manual]
  fail_fast: true
- id: prevent-returning-fastapi-httpexceptions
  name: Prevent returning FastAPI HTTPExceptions
  description: |
    FastAPI `HTTPException`s must be `raise`d to create HTTP responses with status code >= 400. If `return`ed, they become JSON-wrapped HTTP responses with status code 200.
    This hook is limited to resolving return values within the same file.
  language: python
  entry: prevent-returning-fastapi-httpexceptions
  types: ['python']
