- id: markdown-detect-nonref-links
  name: Checking for Markdown non-ref links
  description: |
    This pre-commit hook detects markdown files that contain non-ref link
    types.
  entry: markdown-detect-nonref-links
  language: python
  files: '\.md$'
- id: rego-unsafe-boolean-comparison
  name: Checking for unsafe boolean comparisons in Rego
  description: |
    This pre-commit hook detects unsafe boolean comparisons in Rego that
    could potential cause false-positive and false-negative alerts.
  entry: rego-unsafe-boolean-comparison
  language: python
  files: '\.rego$'
- id: docker-multiline-cmds
  name: Checking for suboptimal use of multiline commands in Dockerfiles
  description: |
    This pre-commit hook detects suboptimal use of multiline commands in
    Dockerfiles. Suboptimal in the sense that if changing them creates
    unclean git diffs.
    More information on https://www.youtube.com/watch?v=BdxdRlTnPEE
  entry: docker-multiline-cmds
  language: python
  types: ['dockerfile']
