name: check

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
          - MacOs
    steps:
      - uses: actions/checkout@v2
      - name: Install uv & tox-uv
        run: |
          python -m pip install uv
          uv tool install tox --with tox-uv
      - name: Run test suite
        run: ./run_tests.sh
      - name: Run pre-commit
        run: |
          uv tool run pre-commit run --all-files --show-diff-on-failure
